dsr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  # Position Controllers ---------------------------------------
  joint1_position:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 500.0, i: 100.0, d: 200.0,  i_clamp: 500}

  joint2_position:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 500.0, i: 100.0, d: 250.0, i_clamp: 500}

  joint3_position:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 300.0, i: 20.0, d: 40.0, i_clamp: 500}

  joint4_position:
    type: position_controllers/JointPositionController
    joint: joint4
    pid: {p: 100.0, i: 0.0, d: 40.0, i_clamp: 500}

  joint5_position:
    type: position_controllers/JointPositionController
    joint: joint5
    pid: {p: 200.0, i: 20.0, d: 25.0, i_clamp: 500}

  joint6_position:
    type: position_controllers/JointPositionController
    joint: joint6
    pid: {p: 300.0, i: 20.0, d: 25.0, i_clamp: 500}



